# Site settings
title: Stanford DAWN | The Stanford DAWN blog.
description: "The Stanford DAWN blog."
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "Shoumik Palkar"
  email: "shoumik@cs.stanford.edu"
  url: "http://dawn.cs.stanford.edu"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
